		dc.l	BackgroundScroll_00	;  0
		dc.l	BackgroundScroll_01	;  1
		dc.l	BackgroundScroll_02	;  2
		dc.l	BackgroundScroll_03	;  3
		dc.l	BackgroundScroll_04	;  4
		dc.l	BackgroundScroll_05	;  5
		dc.l	BackgroundScroll_06	;  6
		dc.l	BackgroundScroll_07	;  7
		dc.l	BackgroundScroll_08	;  8
		dc.l	BackgroundScroll_09	;  9
		dc.l	BackgroundScroll_0A	;  A
		dc.l	BackgroundScroll_0B	;  B
		dc.l	BackgroundScroll_0C	;  C
		dc.l	BackgroundScroll_0D	;  D
		dc.l	BackgroundScroll_0E	;  E
		dc.l	BackgroundScroll_0F	;  F
		dc.l	BackgroundScroll_10	; 10
		dc.l	BackgroundScroll_11	; 11
		dc.l	BackgroundScroll_12	; 12
		dc.l	BackgroundScroll_13	; 13
		dc.l	BackgroundScroll_14	; 14
		dc.l	BackgroundScroll_15	; 15
		dc.l	BackgroundScroll_16	; 16
		dc.l	BackgroundScroll_17	; 17
		dc.l	BackgroundScroll_18	; 18
		dc.l	BackgroundScroll_19	; 19
		dc.l	BackgroundScroll_1A	; 1A
		dc.l	BackgroundScroll_1B	; 1B
		dc.l	BackgroundScroll_1C	; 1C
		dc.l	BackgroundScroll_1D	; 1D
		dc.l	BackgroundScroll_1E	; 1E
		dc.l	BackgroundScroll_1F	; 1F
		dc.l	BackgroundScroll_20	; 20
		dc.l	BackgroundScroll_21	; 21
		dc.l	BackgroundScroll_22	; 22
		dc.l	BackgroundScroll_23	; 23
		dc.l	BackgroundScroll_24	; 24
		dc.l	BackgroundScroll_25	; 25
		dc.l	BackgroundScroll_26	; 26
		dc.l	BackgroundScroll_27	; 27
		dc.l	BackgroundScroll_28	; 28
		dc.l	BackgroundScroll_29	; 29
		dc.l	BackgroundScroll_2A	; 2A
		dc.l	BackgroundScroll_2B	; 2B
		dc.l	BackgroundScroll_2C	; 2C
		dc.l	BackgroundScroll_2D	; 2D
		dc.l	BackgroundScroll_2E	; 2E
		dc.l	BackgroundScroll_2F	; 2F
		dc.l	BackgroundScroll_30	; 30
		dc.l	BackgroundScroll_31	; 31
		dc.l	BackgroundScroll_32	; 32
		dc.l	BackgroundScroll_33	; 33
		dc.l	BackgroundScroll_34	; 34
		dc.l	BackgroundScroll_35	; 35
		dc.l	BackgroundScroll_36	; 36
		dc.l	BackgroundScroll_37	; 37
		dc.l	BackgroundScroll_38	; 38
		dc.l	BackgroundScroll_39	; 39
		dc.l	BackgroundScroll_3A	; 3A
		dc.l	BackgroundScroll_3B	; 3B
		dc.l	BackgroundScroll_3C	; 3C
		dc.l	BackgroundScroll_3D	; 3D
		dc.l	BackgroundScroll_3E	; 3E
		dc.l	BackgroundScroll_3F	; 3F
		dc.l	BackgroundScroll_40	; 40
		dc.l	BackgroundScroll_41	; 41
		dc.l	BackgroundScroll_42	; 42
		dc.l	BackgroundScroll_43	; 43
		dc.l	BackgroundScroll_44	; 44
		dc.l	BackgroundScroll_45	; 45
		dc.l	BackgroundScroll_46	; 46
		dc.l	BackgroundScroll_47	; 47
		dc.l	BackgroundScroll_48	; 48
		dc.l	BackgroundScroll_49	; 49
		dc.l	BackgroundScroll_4A	; 4A
		dc.l	BackgroundScroll_4B	; 4B
		dc.l	BackgroundScroll_4C	; 4C
		dc.l	BackgroundScroll_4D	; 4D
		dc.l	BackgroundScroll_4E	; 4E
		dc.l	BackgroundScroll_4F	; 4F
		dc.l	BackgroundScroll_50	; 50
		dc.l	BackgroundScroll_51	; 51
		dc.l	BackgroundScroll_52	; 52
		dc.l	BackgroundScroll_53	; 53
		dc.l	BackgroundScroll_54	; 54
		dc.l	BackgroundScroll_55	; 55
		dc.l	BackgroundScroll_56	; 56
		dc.l	BackgroundScroll_57	; 57
		dc.l	BackgroundScroll_58	; 58
		dc.l	BackgroundScroll_59	; 59
		dc.l	BackgroundScroll_5A	; 5A
		dc.l	BackgroundScroll_5B	; 5B
		dc.l	BackgroundScroll_5C	; 5C
		dc.l	BackgroundScroll_5D	; 5D
		dc.l	BackgroundScroll_5E	; 5E
		dc.l	BackgroundScroll_5F	; 5F
		dc.l	BackgroundScroll_60	; 60
		dc.l	BackgroundScroll_61	; 61
		dc.l	BackgroundScroll_62	; 62
		dc.l	BackgroundScroll_63	; 63
		dc.l	BackgroundScroll_64	; 64
		dc.l	BackgroundScroll_65	; 65
		dc.l	BackgroundScroll_66	; 66
		dc.l	BackgroundScroll_67	; 67
		dc.l	BackgroundScroll_68	; 68
		dc.l	BackgroundScroll_69	; 69
		dc.l	BackgroundScroll_6A	; 6A
		dc.l	BackgroundScroll_6B	; 6B
		dc.l	BackgroundScroll_6C	; 6C
		dc.l	BackgroundScroll_6D	; 6D
		dc.l	BackgroundScroll_6E	; 6E
		dc.l	BackgroundScroll_6F	; 6F
		dc.l	BackgroundScroll_70	; 70
		dc.l	BackgroundScroll_71	; 71
		dc.l	BackgroundScroll_72	; 72
		dc.l	BackgroundScroll_73	; 73
		dc.l	BackgroundScroll_74	; 74
		dc.l	BackgroundScroll_75	; 75
		dc.l	BackgroundScroll_76	; 76
		dc.l	BackgroundScroll_77	; 77
		dc.l	BackgroundScroll_78	; 78
		dc.l	BackgroundScroll_79	; 79
		dc.l	BackgroundScroll_7A	; 7A
		dc.l	BackgroundScroll_7B	; 7B
		dc.l	BackgroundScroll_7C	; 7C
		dc.l	BackgroundScroll_7D	; 7D
