MapHeader_00:	maphdr	"level/header/00.bin", ForegroundLayout_00, BlockLayout_00, BackgroundLayout_00, EnemyLayout_00
MapHeader_01:	maphdr	"level/header/01.bin", ForegroundLayout_01, BlockLayout_01, BackgroundLayout_01, EnemyLayout_01
MapHeader_02:	maphdr	"level/header/02.bin", ForegroundLayout_02, BlockLayout_02, BackgroundLayout_02, EnemyLayout_02
MapHeader_03:	maphdr	"level/header/03.bin", ForegroundLayout_03, BlockLayout_03, BackgroundLayout_03, EnemyLayout_03
MapHeader_04:	maphdr	"level/header/04.bin", ForegroundLayout_04, BlockLayout_04, BackgroundLayout_04, EnemyLayout_04
MapHeader_05:	maphdr	"level/header/05.bin", ForegroundLayout_05, BlockLayout_05, BackgroundLayout_05, EnemyLayout_05
MapHeader_06:	maphdr	"level/header/06.bin", ForegroundLayout_06, BlockLayout_06, BackgroundLayout_06, EnemyLayout_06
MapHeader_07:	maphdr	"level/header/07.bin", ForegroundLayout_07, BlockLayout_07, BackgroundLayout_07, EnemyLayout_07
MapHeader_08:	maphdr	"level/header/08.bin", ForegroundLayout_08, BlockLayout_08, BackgroundLayout_08, EnemyLayout_08
MapHeader_09:	maphdr	"level/header/09.bin", ForegroundLayout_09, BlockLayout_09, BackgroundLayout_09, EnemyLayout_09
MapHeader_0A:	maphdr	"level/header/0A.bin", ForegroundLayout_0A, BlockLayout_0A, BackgroundLayout_0A, EnemyLayout_0A
MapHeader_0B:	maphdr	"level/header/0B.bin", ForegroundLayout_0B, BlockLayout_0B, BackgroundLayout_0B, EnemyLayout_0B
MapHeader_0C:	maphdr	"level/header/0C.bin", ForegroundLayout_0C, BlockLayout_0C, BackgroundLayout_0C, EnemyLayout_0C
MapHeader_0D:	maphdr	"level/header/0D.bin", ForegroundLayout_0D, BlockLayout_0D, BackgroundLayout_0D, EnemyLayout_0D
MapHeader_0E:	maphdr	"level/header/0E.bin", ForegroundLayout_0E, BlockLayout_0E, BackgroundLayout_0E, EnemyLayout_0E
MapHeader_0F:	maphdr	"level/header/0F.bin", ForegroundLayout_0F, BlockLayout_0F, BackgroundLayout_0F, EnemyLayout_0F
MapHeader_10:	maphdr	"level/header/10.bin", ForegroundLayout_10, BlockLayout_10, BackgroundLayout_10, EnemyLayout_10
MapHeader_11:	maphdr	"level/header/11.bin", ForegroundLayout_11, BlockLayout_11, BackgroundLayout_11, EnemyLayout_11
MapHeader_12:	maphdr	"level/header/12.bin", ForegroundLayout_12, BlockLayout_12, BackgroundLayout_12, EnemyLayout_12
MapHeader_13:	maphdr	"level/header/13.bin", ForegroundLayout_13, BlockLayout_13, BackgroundLayout_13, EnemyLayout_13
MapHeader_14:	maphdr	"level/header/14.bin", ForegroundLayout_14, BlockLayout_14, BackgroundLayout_14, EnemyLayout_14
MapHeader_15:	maphdr	"level/header/15.bin", ForegroundLayout_15, BlockLayout_15, BackgroundLayout_15, EnemyLayout_15
MapHeader_16:	maphdr	"level/header/16.bin", ForegroundLayout_16, BlockLayout_16, BackgroundLayout_16, EnemyLayout_16
MapHeader_17:	maphdr	"level/header/17.bin", ForegroundLayout_17, BlockLayout_17, BackgroundLayout_17, EnemyLayout_17
MapHeader_18:	maphdr	"level/header/18.bin", ForegroundLayout_18, BlockLayout_18, BackgroundLayout_18, EnemyLayout_18
MapHeader_19:	maphdr	"level/header/19.bin", ForegroundLayout_19, BlockLayout_19, BackgroundLayout_19, EnemyLayout_19
MapHeader_1A:	maphdr	"level/header/1A.bin", ForegroundLayout_1A, BlockLayout_1A, BackgroundLayout_1A, EnemyLayout_1A
MapHeader_1B:	maphdr	"level/header/1B.bin", ForegroundLayout_1B, BlockLayout_1B, BackgroundLayout_1B, EnemyLayout_1B
MapHeader_1C:	maphdr	"level/header/1C.bin", ForegroundLayout_1C, BlockLayout_1C, BackgroundLayout_1C, EnemyLayout_1C
MapHeader_1D:	maphdr	"level/header/1D.bin", ForegroundLayout_1D, BlockLayout_1D, BackgroundLayout_1D, EnemyLayout_1D
MapHeader_1E:	maphdr	"level/header/1E.bin", ForegroundLayout_1E, BlockLayout_1E, BackgroundLayout_1E, EnemyLayout_1E
MapHeader_1F:	maphdr	"level/header/1F.bin", ForegroundLayout_1F, BlockLayout_1F, BackgroundLayout_1F, EnemyLayout_1F
MapHeader_20:	maphdr	"level/header/20.bin", ForegroundLayout_20, BlockLayout_20, BackgroundLayout_20, EnemyLayout_20
MapHeader_21:	maphdr	"level/header/21.bin", ForegroundLayout_21, BlockLayout_21, BackgroundLayout_21, EnemyLayout_21
MapHeader_22:	maphdr	"level/header/22.bin", ForegroundLayout_22, BlockLayout_22, BackgroundLayout_22, EnemyLayout_22
MapHeader_23:	maphdr	"level/header/23.bin", ForegroundLayout_23, BlockLayout_23, BackgroundLayout_23, EnemyLayout_23
MapHeader_24:	maphdr	"level/header/24.bin", ForegroundLayout_24, BlockLayout_24, BackgroundLayout_24, EnemyLayout_24
MapHeader_25:	maphdr	"level/header/25.bin", ForegroundLayout_25, BlockLayout_25, BackgroundLayout_25, EnemyLayout_25
MapHeader_26:	maphdr	"level/header/26.bin", ForegroundLayout_26, BlockLayout_26, BackgroundLayout_26, EnemyLayout_26
MapHeader_27:	maphdr	"level/header/27.bin", ForegroundLayout_27, BlockLayout_27, BackgroundLayout_27, EnemyLayout_27
MapHeader_28:	maphdr	"level/header/28.bin", ForegroundLayout_28, BlockLayout_28, BackgroundLayout_28, EnemyLayout_28
MapHeader_29:	maphdr	"level/header/29.bin", ForegroundLayout_29, BlockLayout_29, BackgroundLayout_29, EnemyLayout_29
MapHeader_2A:	maphdr	"level/header/2A.bin", ForegroundLayout_2A, BlockLayout_2A, BackgroundLayout_2A, EnemyLayout_2A
MapHeader_2B:	maphdr	"level/header/2B.bin", ForegroundLayout_2B, BlockLayout_2B, BackgroundLayout_2B, EnemyLayout_2B
MapHeader_2C:	maphdr	"level/header/2C.bin", ForegroundLayout_2C, BlockLayout_2C, BackgroundLayout_2C, EnemyLayout_2C
MapHeader_2D:	maphdr	"level/header/2D.bin", ForegroundLayout_2D, BlockLayout_2D, BackgroundLayout_2D, EnemyLayout_2D
MapHeader_2E:	maphdr	"level/header/2E.bin", ForegroundLayout_2E, BlockLayout_2E, BackgroundLayout_2E, EnemyLayout_2E
MapHeader_2F:	maphdr	"level/header/2F.bin", ForegroundLayout_2F, BlockLayout_2F, BackgroundLayout_2F, EnemyLayout_2F
MapHeader_30:	maphdr	"level/header/30.bin", ForegroundLayout_30, BlockLayout_30, BackgroundLayout_30, EnemyLayout_30
MapHeader_31:	maphdr	"level/header/31.bin", ForegroundLayout_31, BlockLayout_31, BackgroundLayout_31, EnemyLayout_31
MapHeader_32:	maphdr	"level/header/32.bin", ForegroundLayout_32, BlockLayout_32, BackgroundLayout_32, EnemyLayout_32
MapHeader_33:	maphdr	"level/header/33.bin", ForegroundLayout_33, BlockLayout_33, BackgroundLayout_33, EnemyLayout_33
MapHeader_34:	maphdr	"level/header/34.bin", ForegroundLayout_34, BlockLayout_34, BackgroundLayout_34, EnemyLayout_34
MapHeader_35:	maphdr	"level/header/35.bin", ForegroundLayout_35, BlockLayout_35, BackgroundLayout_35, EnemyLayout_35
MapHeader_36:	maphdr	"level/header/36.bin", ForegroundLayout_36, BlockLayout_36, BackgroundLayout_36, EnemyLayout_36
MapHeader_37:	maphdr	"level/header/37.bin", ForegroundLayout_37, BlockLayout_37, BackgroundLayout_37, EnemyLayout_37
MapHeader_38:	maphdr	"level/header/38.bin", ForegroundLayout_38, BlockLayout_38, BackgroundLayout_38, EnemyLayout_38
MapHeader_39:	maphdr	"level/header/39.bin", ForegroundLayout_39, BlockLayout_39, BackgroundLayout_39, EnemyLayout_39
MapHeader_3A:	maphdr	"level/header/3A.bin", ForegroundLayout_3A, BlockLayout_3A, BackgroundLayout_3A, EnemyLayout_3A
MapHeader_3B:	maphdr	"level/header/3B.bin", ForegroundLayout_3B, BlockLayout_3B, BackgroundLayout_3B, EnemyLayout_3B
MapHeader_3C:	maphdr	"level/header/3C.bin", ForegroundLayout_3C, BlockLayout_3C, BackgroundLayout_3C, EnemyLayout_3C
MapHeader_3D:	maphdr	"level/header/3D.bin", ForegroundLayout_3D, BlockLayout_3D, BackgroundLayout_3D, EnemyLayout_3D
MapHeader_3E:	maphdr	"level/header/3E.bin", ForegroundLayout_3E, BlockLayout_3E, BackgroundLayout_3E, EnemyLayout_3E
MapHeader_3F:	maphdr	"level/header/3F.bin", ForegroundLayout_3F, BlockLayout_3F, BackgroundLayout_3F, EnemyLayout_3F
MapHeader_40:	maphdr	"level/header/40.bin", ForegroundLayout_40, BlockLayout_40, BackgroundLayout_40, EnemyLayout_40
MapHeader_41:	maphdr	"level/header/41.bin", ForegroundLayout_41, BlockLayout_41, BackgroundLayout_41, EnemyLayout_41
MapHeader_42:	maphdr	"level/header/42.bin", ForegroundLayout_42, BlockLayout_42, BackgroundLayout_42, EnemyLayout_42
MapHeader_43:	maphdr	"level/header/43.bin", ForegroundLayout_43, BlockLayout_43, BackgroundLayout_43, EnemyLayout_43
MapHeader_44:	maphdr	"level/header/44.bin", ForegroundLayout_44, BlockLayout_44, BackgroundLayout_44, EnemyLayout_44
MapHeader_45:	maphdr	"level/header/45.bin", ForegroundLayout_45, BlockLayout_45, BackgroundLayout_45, EnemyLayout_45
MapHeader_46:	maphdr	"level/header/46.bin", ForegroundLayout_46, BlockLayout_46, BackgroundLayout_46, EnemyLayout_46
MapHeader_47:	maphdr	"level/header/47.bin", ForegroundLayout_47, BlockLayout_47, BackgroundLayout_47, EnemyLayout_47
MapHeader_48:	maphdr	"level/header/48.bin", ForegroundLayout_48, BlockLayout_48, BackgroundLayout_48, EnemyLayout_48
MapHeader_49:	maphdr	"level/header/49.bin", ForegroundLayout_49, BlockLayout_49, BackgroundLayout_49, EnemyLayout_49
MapHeader_4A:	maphdr	"level/header/4A.bin", ForegroundLayout_4A, BlockLayout_4A, BackgroundLayout_4A, EnemyLayout_4A
MapHeader_4B:	maphdr	"level/header/4B.bin", ForegroundLayout_4B, BlockLayout_4B, BackgroundLayout_4B, EnemyLayout_4B
MapHeader_4C:	maphdr	"level/header/4C.bin", ForegroundLayout_4C, BlockLayout_4C, BackgroundLayout_4C, EnemyLayout_4C
MapHeader_4D:	maphdr	"level/header/4D.bin", ForegroundLayout_4D, BlockLayout_4D, BackgroundLayout_4D, EnemyLayout_4D
MapHeader_4E:	maphdr	"level/header/4E.bin", ForegroundLayout_4E, BlockLayout_4E, BackgroundLayout_4E, EnemyLayout_4E
MapHeader_4F:	maphdr	"level/header/4F.bin", ForegroundLayout_4F, BlockLayout_4F, BackgroundLayout_4F, EnemyLayout_4F
MapHeader_50:	maphdr	"level/header/50.bin", ForegroundLayout_50, BlockLayout_50, BackgroundLayout_50, EnemyLayout_50
MapHeader_51:	maphdr	"level/header/51.bin", ForegroundLayout_51, BlockLayout_51, BackgroundLayout_51, EnemyLayout_51
MapHeader_52:	maphdr	"level/header/52.bin", ForegroundLayout_52, BlockLayout_52, BackgroundLayout_52, EnemyLayout_52
MapHeader_53:	maphdr	"level/header/53.bin", ForegroundLayout_53, BlockLayout_53, BackgroundLayout_53, EnemyLayout_53
MapHeader_54:	maphdr	"level/header/54.bin", ForegroundLayout_54, BlockLayout_54, BackgroundLayout_54, EnemyLayout_54
MapHeader_55:	maphdr	"level/header/55.bin", ForegroundLayout_55, BlockLayout_55, BackgroundLayout_55, EnemyLayout_55
MapHeader_56:	maphdr	"level/header/56.bin", ForegroundLayout_56, BlockLayout_56, BackgroundLayout_56, EnemyLayout_56
MapHeader_57:	maphdr	"level/header/57.bin", ForegroundLayout_57, BlockLayout_57, BackgroundLayout_57, EnemyLayout_57
MapHeader_58:	maphdr	"level/header/58.bin", ForegroundLayout_58, BlockLayout_58, BackgroundLayout_58, EnemyLayout_58
MapHeader_59:	maphdr	"level/header/59.bin", ForegroundLayout_59, BlockLayout_59, BackgroundLayout_59, EnemyLayout_59
MapHeader_5A:	maphdr	"level/header/5A.bin", ForegroundLayout_5A, BlockLayout_5A, BackgroundLayout_5A, EnemyLayout_5A
MapHeader_5B:	maphdr	"level/header/5B.bin", ForegroundLayout_5B, BlockLayout_5B, BackgroundLayout_5B, EnemyLayout_5B
MapHeader_5C:	maphdr	"level/header/5C.bin", ForegroundLayout_5C, BlockLayout_5C, BackgroundLayout_5C, EnemyLayout_5C
MapHeader_5D:	maphdr	"level/header/5D.bin", ForegroundLayout_5D, BlockLayout_5D, BackgroundLayout_5D, EnemyLayout_5D
MapHeader_5E:	maphdr	"level/header/5E.bin", ForegroundLayout_5E, BlockLayout_5E, BackgroundLayout_5E, EnemyLayout_5E
MapHeader_5F:	maphdr	"level/header/5F.bin", ForegroundLayout_5F, BlockLayout_5F, BackgroundLayout_5F, EnemyLayout_5F
MapHeader_60:	maphdr	"level/header/60.bin", ForegroundLayout_60, BlockLayout_60, BackgroundLayout_60, EnemyLayout_60
MapHeader_61:	maphdr	"level/header/61.bin", ForegroundLayout_61, BlockLayout_61, BackgroundLayout_61, EnemyLayout_61
MapHeader_62:	maphdr	"level/header/62.bin", ForegroundLayout_62, BlockLayout_62, BackgroundLayout_62, EnemyLayout_62
MapHeader_63:	maphdr	"level/header/63.bin", ForegroundLayout_63, BlockLayout_63, BackgroundLayout_63, EnemyLayout_63
MapHeader_64:	maphdr	"level/header/64.bin", ForegroundLayout_64, BlockLayout_64, BackgroundLayout_64, EnemyLayout_64
MapHeader_65:	maphdr	"level/header/65.bin", ForegroundLayout_65, BlockLayout_65, BackgroundLayout_65, EnemyLayout_65
MapHeader_66:	maphdr	"level/header/66.bin", ForegroundLayout_66, BlockLayout_66, BackgroundLayout_66, EnemyLayout_66
MapHeader_67:	maphdr	"level/header/67.bin", ForegroundLayout_67, BlockLayout_67, BackgroundLayout_67, EnemyLayout_67
MapHeader_68:	maphdr	"level/header/68.bin", ForegroundLayout_68, BlockLayout_68, BackgroundLayout_68, EnemyLayout_68
MapHeader_69:	maphdr	"level/header/69.bin", ForegroundLayout_69, BlockLayout_69, BackgroundLayout_69, EnemyLayout_69
MapHeader_6A:	maphdr	"level/header/6A.bin", ForegroundLayout_6A, BlockLayout_6A, BackgroundLayout_6A, EnemyLayout_6A
MapHeader_6B:	maphdr	"level/header/6B.bin", ForegroundLayout_6B, BlockLayout_6B, BackgroundLayout_6B, EnemyLayout_6B
MapHeader_6C:	maphdr	"level/header/6C.bin", ForegroundLayout_6C, BlockLayout_6C, BackgroundLayout_6C, EnemyLayout_6C
MapHeader_6D:	maphdr	"level/header/6D.bin", ForegroundLayout_6D, BlockLayout_6D, BackgroundLayout_6D, EnemyLayout_6D
MapHeader_6E:	maphdr	"level/header/6E.bin", ForegroundLayout_6E, BlockLayout_6E, BackgroundLayout_6E, EnemyLayout_6E
MapHeader_6F:	maphdr	"level/header/6F.bin", ForegroundLayout_6F, BlockLayout_6F, BackgroundLayout_6F, EnemyLayout_6F
MapHeader_70:	maphdr	"level/header/70.bin", ForegroundLayout_70, BlockLayout_70, BackgroundLayout_70, EnemyLayout_70
MapHeader_71:	maphdr	"level/header/71.bin", ForegroundLayout_71, BlockLayout_71, BackgroundLayout_71, EnemyLayout_71
MapHeader_72:	maphdr	"level/header/72.bin", ForegroundLayout_72, BlockLayout_72, BackgroundLayout_72, EnemyLayout_72
MapHeader_73:	maphdr	"level/header/73.bin", ForegroundLayout_73, BlockLayout_73, BackgroundLayout_73, EnemyLayout_73
MapHeader_74:	maphdr	"level/header/74.bin", ForegroundLayout_74, BlockLayout_74, BackgroundLayout_74, EnemyLayout_74
MapHeader_75:	maphdr	"level/header/75.bin", ForegroundLayout_75, BlockLayout_75, BackgroundLayout_75, EnemyLayout_75
MapHeader_76:	maphdr	"level/header/76.bin", ForegroundLayout_76, BlockLayout_76, BackgroundLayout_76, EnemyLayout_76
MapHeader_77:	maphdr	"level/header/77.bin", ForegroundLayout_77, BlockLayout_77, BackgroundLayout_77, EnemyLayout_77
MapHeader_78:	maphdr	"level/header/78.bin", ForegroundLayout_78, BlockLayout_78, BackgroundLayout_78, EnemyLayout_78
MapHeader_79:	maphdr	"level/header/79.bin", ForegroundLayout_79, BlockLayout_79, BackgroundLayout_79, EnemyLayout_79
MapHeader_7A:	maphdr	"level/header/7A.bin", ForegroundLayout_7A, BlockLayout_7A, BackgroundLayout_7A, EnemyLayout_7A
MapHeader_7B:	maphdr	"level/header/7B.bin", ForegroundLayout_7B, BlockLayout_7B, BackgroundLayout_7B, EnemyLayout_7B
MapHeader_7C:	maphdr	"level/header/7C.bin", ForegroundLayout_7C, BlockLayout_7C, BackgroundLayout_7C, EnemyLayout_7C
MapHeader_7D:	maphdr	"level/header/7D.bin", ForegroundLayout_7D, BlockLayout_7D, BackgroundLayout_7D, EnemyLayout_7D
