		dc.w	PlatformLayout_00-PlatformLayout_BaseAddress	;  0
		dc.w	PlatformLayout_01-PlatformLayout_BaseAddress	;  1
		dc.w	PlatformLayout_02-PlatformLayout_BaseAddress	;  2
		dc.w	PlatformLayout_03-PlatformLayout_BaseAddress	;  3
		dc.w	PlatformLayout_04-PlatformLayout_BaseAddress	;  4
		dc.w	PlatformLayout_05-PlatformLayout_BaseAddress	;  5
		dc.w	PlatformLayout_06-PlatformLayout_BaseAddress	;  6
		dc.w	PlatformLayout_07-PlatformLayout_BaseAddress	;  7
		dc.w	PlatformLayout_08-PlatformLayout_BaseAddress	;  8
		dc.w	PlatformLayout_09-PlatformLayout_BaseAddress	;  9
		dc.w	PlatformLayout_0A-PlatformLayout_BaseAddress	;  A
		dc.w	PlatformLayout_0B-PlatformLayout_BaseAddress	;  B
		dc.w	PlatformLayout_0C-PlatformLayout_BaseAddress	;  C
		dc.w	PlatformLayout_0D-PlatformLayout_BaseAddress	;  D
		dc.w	PlatformLayout_0E-PlatformLayout_BaseAddress	;  E
		dc.w	PlatformLayout_0F-PlatformLayout_BaseAddress	;  F
		dc.w	PlatformLayout_10-PlatformLayout_BaseAddress	; 10
		dc.w	PlatformLayout_11-PlatformLayout_BaseAddress	; 11
		dc.w	PlatformLayout_12-PlatformLayout_BaseAddress	; 12
		dc.w	PlatformLayout_13-PlatformLayout_BaseAddress	; 13
		dc.w	PlatformLayout_14-PlatformLayout_BaseAddress	; 14
		dc.w	PlatformLayout_15-PlatformLayout_BaseAddress	; 15
		dc.w	PlatformLayout_16-PlatformLayout_BaseAddress	; 16
		dc.w	PlatformLayout_17-PlatformLayout_BaseAddress	; 17
		dc.w	PlatformLayout_18-PlatformLayout_BaseAddress	; 18
		dc.w	PlatformLayout_19-PlatformLayout_BaseAddress	; 19
		dc.w	PlatformLayout_1A-PlatformLayout_BaseAddress	; 1A
		dc.w	PlatformLayout_1B-PlatformLayout_BaseAddress	; 1B
		dc.w	PlatformLayout_1C-PlatformLayout_BaseAddress	; 1C
		dc.w	PlatformLayout_1D-PlatformLayout_BaseAddress	; 1D
		dc.w	PlatformLayout_1E-PlatformLayout_BaseAddress	; 1E
		dc.w	PlatformLayout_1F-PlatformLayout_BaseAddress	; 1F
		dc.w	PlatformLayout_20-PlatformLayout_BaseAddress	; 20
		dc.w	PlatformLayout_21-PlatformLayout_BaseAddress	; 21
		dc.w	PlatformLayout_22-PlatformLayout_BaseAddress	; 22
		dc.w	PlatformLayout_23-PlatformLayout_BaseAddress	; 23
		dc.w	PlatformLayout_24-PlatformLayout_BaseAddress	; 24
		dc.w	PlatformLayout_25-PlatformLayout_BaseAddress	; 25
		dc.w	PlatformLayout_26-PlatformLayout_BaseAddress	; 26
		dc.w	PlatformLayout_27-PlatformLayout_BaseAddress	; 27
		dc.w	PlatformLayout_28-PlatformLayout_BaseAddress	; 28
		dc.w	PlatformLayout_29-PlatformLayout_BaseAddress	; 29
		dc.w	PlatformLayout_2A-PlatformLayout_BaseAddress	; 2A
		dc.w	PlatformLayout_2B-PlatformLayout_BaseAddress	; 2B
		dc.w	PlatformLayout_2C-PlatformLayout_BaseAddress	; 2C
		dc.w	PlatformLayout_2D-PlatformLayout_BaseAddress	; 2D
		dc.w	PlatformLayout_2E-PlatformLayout_BaseAddress	; 2E
		dc.w	PlatformLayout_2F-PlatformLayout_BaseAddress	; 2F
		dc.w	PlatformLayout_30-PlatformLayout_BaseAddress	; 30
		dc.w	PlatformLayout_31-PlatformLayout_BaseAddress	; 31
		dc.w	PlatformLayout_32-PlatformLayout_BaseAddress	; 32
		dc.w	PlatformLayout_33-PlatformLayout_BaseAddress	; 33
		dc.w	PlatformLayout_34-PlatformLayout_BaseAddress	; 34
		dc.w	PlatformLayout_35-PlatformLayout_BaseAddress	; 35
		dc.w	PlatformLayout_36-PlatformLayout_BaseAddress	; 36
		dc.w	PlatformLayout_37-PlatformLayout_BaseAddress	; 37
		dc.w	PlatformLayout_38-PlatformLayout_BaseAddress	; 38
		dc.w	PlatformLayout_39-PlatformLayout_BaseAddress	; 39
		dc.w	PlatformLayout_3A-PlatformLayout_BaseAddress	; 3A
		dc.w	PlatformLayout_3B-PlatformLayout_BaseAddress	; 3B
		dc.w	PlatformLayout_3C-PlatformLayout_BaseAddress	; 3C
		dc.w	PlatformLayout_3D-PlatformLayout_BaseAddress	; 3D
		dc.w	PlatformLayout_3E-PlatformLayout_BaseAddress	; 3E
		dc.w	PlatformLayout_3F-PlatformLayout_BaseAddress	; 3F
		dc.w	PlatformLayout_40-PlatformLayout_BaseAddress	; 40
		dc.w	PlatformLayout_41-PlatformLayout_BaseAddress	; 41
		dc.w	PlatformLayout_42-PlatformLayout_BaseAddress	; 42
		dc.w	PlatformLayout_43-PlatformLayout_BaseAddress	; 43
		dc.w	PlatformLayout_44-PlatformLayout_BaseAddress	; 44
		dc.w	PlatformLayout_45-PlatformLayout_BaseAddress	; 45
		dc.w	PlatformLayout_46-PlatformLayout_BaseAddress	; 46
		dc.w	PlatformLayout_47-PlatformLayout_BaseAddress	; 47
		dc.w	PlatformLayout_48-PlatformLayout_BaseAddress	; 48
		dc.w	PlatformLayout_49-PlatformLayout_BaseAddress	; 49
		dc.w	PlatformLayout_4A-PlatformLayout_BaseAddress	; 4A
		dc.w	PlatformLayout_4B-PlatformLayout_BaseAddress	; 4B
		dc.w	PlatformLayout_4C-PlatformLayout_BaseAddress	; 4C
		dc.w	PlatformLayout_4D-PlatformLayout_BaseAddress	; 4D
		dc.w	PlatformLayout_4E-PlatformLayout_BaseAddress	; 4E
		dc.w	PlatformLayout_4F-PlatformLayout_BaseAddress	; 4F
		dc.w	PlatformLayout_50-PlatformLayout_BaseAddress	; 50
		dc.w	PlatformLayout_51-PlatformLayout_BaseAddress	; 51
		dc.w	PlatformLayout_52-PlatformLayout_BaseAddress	; 52
		dc.w	PlatformLayout_53-PlatformLayout_BaseAddress	; 53
		dc.w	PlatformLayout_54-PlatformLayout_BaseAddress	; 54
		dc.w	PlatformLayout_55-PlatformLayout_BaseAddress	; 55
		dc.w	PlatformLayout_56-PlatformLayout_BaseAddress	; 56
		dc.w	PlatformLayout_57-PlatformLayout_BaseAddress	; 57
		dc.w	PlatformLayout_58-PlatformLayout_BaseAddress	; 58
		dc.w	PlatformLayout_59-PlatformLayout_BaseAddress	; 59
		dc.w	PlatformLayout_5A-PlatformLayout_BaseAddress	; 5A
		dc.w	PlatformLayout_5B-PlatformLayout_BaseAddress	; 5B
		dc.w	PlatformLayout_5C-PlatformLayout_BaseAddress	; 5C
		dc.w	PlatformLayout_5D-PlatformLayout_BaseAddress	; 5D
		dc.w	PlatformLayout_5E-PlatformLayout_BaseAddress	; 5E
		dc.w	PlatformLayout_5F-PlatformLayout_BaseAddress	; 5F
		dc.w	PlatformLayout_60-PlatformLayout_BaseAddress	; 60
		dc.w	PlatformLayout_61-PlatformLayout_BaseAddress	; 61
		dc.w	PlatformLayout_62-PlatformLayout_BaseAddress	; 62
		dc.w	PlatformLayout_63-PlatformLayout_BaseAddress	; 63
		dc.w	PlatformLayout_64-PlatformLayout_BaseAddress	; 64
		dc.w	PlatformLayout_65-PlatformLayout_BaseAddress	; 65
		dc.w	PlatformLayout_66-PlatformLayout_BaseAddress	; 66
		dc.w	PlatformLayout_67-PlatformLayout_BaseAddress	; 67
		dc.w	PlatformLayout_68-PlatformLayout_BaseAddress	; 68
		dc.w	PlatformLayout_69-PlatformLayout_BaseAddress	; 69
		dc.w	PlatformLayout_6A-PlatformLayout_BaseAddress	; 6A
		dc.w	PlatformLayout_6B-PlatformLayout_BaseAddress	; 6B
		dc.w	PlatformLayout_6C-PlatformLayout_BaseAddress	; 6C
		dc.w	PlatformLayout_6D-PlatformLayout_BaseAddress	; 6D
		dc.w	PlatformLayout_6E-PlatformLayout_BaseAddress	; 6E
		dc.w	PlatformLayout_6F-PlatformLayout_BaseAddress	; 6F
		dc.w	PlatformLayout_70-PlatformLayout_BaseAddress	; 70
		dc.w	PlatformLayout_71-PlatformLayout_BaseAddress	; 71
		dc.w	PlatformLayout_72-PlatformLayout_BaseAddress	; 72
		dc.w	PlatformLayout_73-PlatformLayout_BaseAddress	; 73
		dc.w	PlatformLayout_74-PlatformLayout_BaseAddress	; 74
		dc.w	PlatformLayout_75-PlatformLayout_BaseAddress	; 75
		dc.w	PlatformLayout_76-PlatformLayout_BaseAddress	; 76
		dc.w	PlatformLayout_77-PlatformLayout_BaseAddress	; 77
		dc.w	PlatformLayout_78-PlatformLayout_BaseAddress	; 78
		dc.w	PlatformLayout_79-PlatformLayout_BaseAddress	; 79
		dc.w	PlatformLayout_7A-PlatformLayout_BaseAddress	; 7A
		dc.w	PlatformLayout_7B-PlatformLayout_BaseAddress	; 7B
		dc.w	PlatformLayout_7C-PlatformLayout_BaseAddress	; 7C
		dc.w	PlatformLayout_7D-PlatformLayout_BaseAddress	; 7D
